from .image_resize import (
    NODE_CLASS_MAPPINGS as IMAGE_RESIZE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_RESIZE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .inpaint_crop_stitch import (
    NODE_CLASS_MAPPINGS as INPAINT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as INPAINT_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **IMAGE_RESIZE_NODE_CLASS_MAPPINGS,
    **INPAINT_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_RESIZE_NODE_DISPLAY_NAME_MAPPINGS,
    **INPAINT_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
